// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mti.OrderManagement.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mti.OrderManagement.Persistence.Migrations
{
    [DbContext(typeof(OrdersContext))]
    [Migration("20250819071619_initOrders")]
    partial class initOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.InsuredAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BookValue")
                        .HasColumnType("numeric");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("Parties_AssetId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("InsuredAssets", "orders");
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("Parties_TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Policies_TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Products_TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders", "orders");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrderedForId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("Products_CoverageLevelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Products_CoverageTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Products_ProductFeatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Products_ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderedForId");

                    b.HasIndex("OrderId", "Seq", "Products_ProductId", "Products_ProductFeatureId", "Products_CoverageTypeId", "Products_CoverageLevelId")
                        .IsUnique();

                    b.ToTable("OrderItems", "orders");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.OrderItemRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderRoleTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Parties_PartyId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("OrderRoleTypeId");

                    b.HasIndex("Seq", "OrderItemId", "OrderRoleTypeId", "Parties_PartyId")
                        .IsUnique();

                    b.ToTable("OrderItemRoles", "orders");
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.PoliciesAgreementItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Policies_AgreementItemId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.ToTable("PoliciesAgreementItems", "orders");
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.Types.OrderRoleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("OrderRoleTypes", "orders");
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.SalesOrder", b =>
                {
                    b.HasBaseType("Mti.OrderManagement.Domain.Orders.Order");

                    b.ToTable("SalesOrders", "orders");
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.SalesOrderItem", b =>
                {
                    b.HasBaseType("Mti.OrderManagement.Domain.Orders.OrderItem");

                    b.ToTable("SalesOrderItems", "orders");
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.MtiOriginalSalesOrder", b =>
                {
                    b.HasBaseType("Mti.OrderManagement.Domain.Orders.SalesOrder");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date");

                    b.HasIndex("SaleDate", "LoanNumber")
                        .IsUnique();

                    b.ToTable("MtiOriginalSalesOrders", "orders");
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.MtiOriginalSalesOrderItem", b =>
                {
                    b.HasBaseType("Mti.OrderManagement.Domain.Orders.SalesOrderItem");

                    b.Property<decimal>("AccidentPerDriver")
                        .HasColumnType("numeric");

                    b.Property<string>("Campaign")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CollateralNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerInfoNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("DamageInsurePerTime")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DamageLifePerPerson")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DamageLifePerTime")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Deduct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InsureDriver")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("InsuredAssetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MedicalInsure")
                        .HasColumnType("numeric");

                    b.Property<long?>("OriginalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Package")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PayPlan")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("PolicyEffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PolicyExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("PolicyNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PolicyPreviousNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RefDetailNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RefNoticeNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RefPolicyType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RefQuotation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("SumInsure")
                        .HasColumnType("numeric");

                    b.Property<string>("SystemId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleBrand")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<float?>("VehicleCc")
                        .HasColumnType("real");

                    b.Property<string>("VehicleChassis")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VehicleCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("VehicleColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VehicleEngine")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("VehicleManufactoringYear")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleModel")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int?>("VehiclePassenger")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleRegisterNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleRegisterProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("VehicleRegisterYear")
                        .HasColumnType("integer");

                    b.Property<float?>("VehicleSeat")
                        .HasColumnType("real");

                    b.Property<float?>("VehicleTonnage")
                        .HasColumnType("real");

                    b.Property<float?>("VehicleWeight")
                        .HasColumnType("real");

                    b.Property<string>("Workshop")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasIndex("InsuredAssetId");

                    b.HasIndex("OriginalId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("MtiOriginalSalesOrderItems", "orders");
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("Mti.OrderManagement.Domain.Orders.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.OrderManagement.Domain.Orders.OrderItem", "OrderedFor")
                        .WithMany()
                        .HasForeignKey("OrderedForId");

                    b.Navigation("Order");

                    b.Navigation("OrderedFor");
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.OrderItemRole", b =>
                {
                    b.HasOne("Mti.OrderManagement.Domain.Orders.OrderItem", "OrderItem")
                        .WithMany("Roles")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.OrderManagement.Domain.Orders.Types.OrderRoleType", "OrderRoleType")
                        .WithMany()
                        .HasForeignKey("OrderRoleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("OrderRoleType");
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.PoliciesAgreementItem", b =>
                {
                    b.HasOne("Mti.OrderManagement.Domain.Orders.OrderItem", "OrderItem")
                        .WithMany("AgreementItems")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.SalesOrder", b =>
                {
                    b.HasOne("Mti.OrderManagement.Domain.Orders.Order", null)
                        .WithOne()
                        .HasForeignKey("Mti.OrderManagement.Domain.Orders.SalesOrder", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.SalesOrderItem", b =>
                {
                    b.HasOne("Mti.OrderManagement.Domain.Orders.OrderItem", null)
                        .WithOne()
                        .HasForeignKey("Mti.OrderManagement.Domain.Orders.SalesOrderItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.MtiOriginalSalesOrder", b =>
                {
                    b.HasOne("Mti.OrderManagement.Domain.Orders.SalesOrder", null)
                        .WithOne()
                        .HasForeignKey("Mti.OrderManagement.Domain.Orders.MtiOriginalSalesOrder", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.MtiOriginalSalesOrderItem", b =>
                {
                    b.HasOne("Mti.OrderManagement.Domain.Orders.SalesOrderItem", null)
                        .WithOne()
                        .HasForeignKey("Mti.OrderManagement.Domain.Orders.MtiOriginalSalesOrderItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.OrderManagement.Domain.Orders.InsuredAsset", "InsuredAsset")
                        .WithMany()
                        .HasForeignKey("InsuredAssetId");

                    b.Navigation("InsuredAsset");
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Mti.OrderManagement.Domain.Orders.OrderItem", b =>
                {
                    b.Navigation("AgreementItems");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
