<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a9f8ce5a-7754-40e9-9792-480da4cf84e7</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.GuardClauses" Version="5.0.0" />
    <PackageReference Include="Confluent.Kafka" Version="2.11.0" />
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mti.PartyManagement.Domain\Mti.PartyManagement.Domain.csproj" />
    <ProjectReference Include="..\Mti.PartyManagement.Messaging\Mti.PartyManagement.Messaging.csproj" />
    <ProjectReference Include="..\Mti.PartyManagement.Persistence\Mti.PartyManagement.Persistence.csproj" />
  </ItemGroup>

</Project>
