services:
  mti.partymanagement.services.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8083
      - ASPNETCORE_HTTPS_PORTS=8084
      - ConnectionStrings__PartiesDb=Server=localhost;TrustServerCertificate=True;User Id=postgres;Password=animalfarm888
      - Kafka__BootstrapServers=localhost:9092
    ports:
      - "8083"
      - "8084"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro