<Project>
	<PropertyGroup>
		<ManagePackageVersionCentrally>true</ManagePackageVersionCentrally>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.8" />
		<PackageVersion Include="FluentValidation" Version="12.0.0" />
		<PackageVersion Include="Microsoft.Data.SqlClient" Version="6.0.2" />
		<PackageVersion Include="MediatR" Version="13.0.0" />
		<PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	</ItemGroup>
</Project>
