// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mti.PartyManagement.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mti.PartyManagement.Persistence.Migrations
{
    [DbContext(typeof(PartiesContext))]
    partial class PartiesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("parties")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Assets", "parties");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.AssetRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetRoleTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetRoleTypeId");

                    b.HasIndex("PartyId");

                    b.ToTable("AssetRoles", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.ContactMechanism", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactMechanismTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContactMechanismTypeId");

                    b.ToTable("ContactMechanisms", "parties");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NationalityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PartyTitleId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NationalityId");

                    b.HasIndex("PartyTitleId");

                    b.ToTable("Parties", "parties");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.PartyContactMechanism", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactMechanismId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContactMechanismId");

                    b.HasIndex("PartyId");

                    b.ToTable("PartyContactMechanisms", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.PartyRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartyRoleTypeId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PartyRoleTypeId");

                    b.HasIndex("PartyId", "PartyRoleTypeId")
                        .IsUnique();

                    b.ToTable("PartyRoles", "parties");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.PartyRoleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PartyRoleTypes", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Types.AgentChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AgentChannels", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Types.AgentMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AgentMasters", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Types.AssetRoleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AssetRoleTypes", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Types.ContactMechanismType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ContactMechanismTypes", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Types.Nationality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Nationalities", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Types.PartyTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOrganization")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PartyTitles", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Vehicle", b =>
                {
                    b.HasBaseType("Mti.PartyManagement.Domain.Parties.Asset");

                    b.Property<string>("Brand")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<float?>("Cc")
                        .HasColumnType("real");

                    b.Property<string>("Chassis")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Engine")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int?>("Passenger")
                        .HasColumnType("integer");

                    b.Property<string>("RegisterNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RegisterProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RegisterYear")
                        .HasColumnType("integer");

                    b.Property<float?>("Seat")
                        .HasColumnType("real");

                    b.Property<float?>("Tonnage")
                        .HasColumnType("real");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.ToTable("Vehicles", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.PostalAddresse", b =>
                {
                    b.HasBaseType("Mti.PartyManagement.Domain.Parties.ContactMechanism");

                    b.Property<string>("Alley")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Building")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("District")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Floor")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Province")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Road")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Room")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SubDistrict")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Village")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VillageNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasIndex("Name");

                    b.ToTable("PostalAddresses", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Organization", b =>
                {
                    b.HasBaseType("Mti.PartyManagement.Domain.Parties.Party");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Reference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasIndex("Name");

                    b.HasIndex("Reference");

                    b.ToTable("Organizations", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Person", b =>
                {
                    b.HasBaseType("Mti.PartyManagement.Domain.Parties.Party");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CardId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.HasIndex("CardId");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("People", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Agent", b =>
                {
                    b.HasBaseType("Mti.PartyManagement.Domain.Parties.PartyRole");

                    b.Property<Guid?>("AgentChannelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentMasterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ConfigCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("License")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StaffCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasIndex("AgentChannelId");

                    b.HasIndex("AgentMasterId");

                    b.HasIndex("Name");

                    b.HasIndex("Number", "ClientNumber")
                        .IsUnique();

                    b.ToTable("Agents", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.InsuredParty", b =>
                {
                    b.HasBaseType("Mti.PartyManagement.Domain.Parties.PartyRole");

                    b.ToTable("InsuredParties", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Invoice", b =>
                {
                    b.HasBaseType("Mti.PartyManagement.Domain.Parties.PartyRole");

                    b.ToTable("Invoices", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.InformalOrganization", b =>
                {
                    b.HasBaseType("Mti.PartyManagement.Domain.Parties.Organization");

                    b.ToTable("InformalOrganizations", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.LegalOrganization", b =>
                {
                    b.HasBaseType("Mti.PartyManagement.Domain.Parties.Organization");

                    b.Property<string>("FederalTaxIdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasIndex("FederalTaxIdNumber");

                    b.ToTable("LegalOrganizations", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Insured", b =>
                {
                    b.HasBaseType("Mti.PartyManagement.Domain.Parties.InsuredParty");

                    b.ToTable("Insureds", "parties");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.AssetRole", b =>
                {
                    b.HasOne("Mti.PartyManagement.Domain.Parties.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.PartyManagement.Domain.Parties.Types.AssetRoleType", "AssetRoleType")
                        .WithMany()
                        .HasForeignKey("AssetRoleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.PartyManagement.Domain.Parties.Party", "Party")
                        .WithMany("AssetRoles")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("AssetRoleType");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.ContactMechanism", b =>
                {
                    b.HasOne("Mti.PartyManagement.Domain.Parties.Types.ContactMechanismType", "ContactMechanismType")
                        .WithMany()
                        .HasForeignKey("ContactMechanismTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactMechanismType");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Party", b =>
                {
                    b.HasOne("Mti.PartyManagement.Domain.Parties.Types.Nationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId");

                    b.HasOne("Mti.PartyManagement.Domain.Parties.Types.PartyTitle", "PartyTitle")
                        .WithMany()
                        .HasForeignKey("PartyTitleId");

                    b.Navigation("Nationality");

                    b.Navigation("PartyTitle");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.PartyContactMechanism", b =>
                {
                    b.HasOne("Mti.PartyManagement.Domain.Parties.ContactMechanism", "ContactMechanism")
                        .WithMany("PartyContactMechanisms")
                        .HasForeignKey("ContactMechanismId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.PartyManagement.Domain.Parties.Party", "Party")
                        .WithMany("PartyContactMechanisms")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactMechanism");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.PartyRole", b =>
                {
                    b.HasOne("Mti.PartyManagement.Domain.Parties.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.PartyManagement.Domain.Parties.PartyRoleType", "PartyRoleType")
                        .WithMany()
                        .HasForeignKey("PartyRoleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");

                    b.Navigation("PartyRoleType");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Vehicle", b =>
                {
                    b.HasOne("Mti.PartyManagement.Domain.Parties.Asset", null)
                        .WithOne()
                        .HasForeignKey("Mti.PartyManagement.Domain.Parties.Vehicle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.PostalAddresse", b =>
                {
                    b.HasOne("Mti.PartyManagement.Domain.Parties.ContactMechanism", null)
                        .WithOne()
                        .HasForeignKey("Mti.PartyManagement.Domain.Parties.PostalAddresse", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Organization", b =>
                {
                    b.HasOne("Mti.PartyManagement.Domain.Parties.Party", null)
                        .WithOne()
                        .HasForeignKey("Mti.PartyManagement.Domain.Parties.Organization", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Person", b =>
                {
                    b.HasOne("Mti.PartyManagement.Domain.Parties.Party", null)
                        .WithOne()
                        .HasForeignKey("Mti.PartyManagement.Domain.Parties.Person", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Agent", b =>
                {
                    b.HasOne("Mti.PartyManagement.Domain.Parties.Types.AgentChannel", "AgentChannel")
                        .WithMany()
                        .HasForeignKey("AgentChannelId");

                    b.HasOne("Mti.PartyManagement.Domain.Parties.Types.AgentMaster", "AgentMaster")
                        .WithMany()
                        .HasForeignKey("AgentMasterId");

                    b.HasOne("Mti.PartyManagement.Domain.Parties.PartyRole", null)
                        .WithOne()
                        .HasForeignKey("Mti.PartyManagement.Domain.Parties.Agent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentChannel");

                    b.Navigation("AgentMaster");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.InsuredParty", b =>
                {
                    b.HasOne("Mti.PartyManagement.Domain.Parties.PartyRole", null)
                        .WithOne()
                        .HasForeignKey("Mti.PartyManagement.Domain.Parties.InsuredParty", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Invoice", b =>
                {
                    b.HasOne("Mti.PartyManagement.Domain.Parties.PartyRole", null)
                        .WithOne()
                        .HasForeignKey("Mti.PartyManagement.Domain.Parties.Invoice", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.InformalOrganization", b =>
                {
                    b.HasOne("Mti.PartyManagement.Domain.Parties.Organization", null)
                        .WithOne()
                        .HasForeignKey("Mti.PartyManagement.Domain.Parties.InformalOrganization", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.LegalOrganization", b =>
                {
                    b.HasOne("Mti.PartyManagement.Domain.Parties.Organization", null)
                        .WithOne()
                        .HasForeignKey("Mti.PartyManagement.Domain.Parties.LegalOrganization", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Insured", b =>
                {
                    b.HasOne("Mti.PartyManagement.Domain.Parties.InsuredParty", null)
                        .WithOne()
                        .HasForeignKey("Mti.PartyManagement.Domain.Parties.Insured", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.ContactMechanism", b =>
                {
                    b.Navigation("PartyContactMechanisms");
                });

            modelBuilder.Entity("Mti.PartyManagement.Domain.Parties.Party", b =>
                {
                    b.Navigation("AssetRoles");

                    b.Navigation("PartyContactMechanisms");
                });
#pragma warning restore 612, 618
        }
    }
}
