// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mti.ProductManagement.Persistance;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mti.ProductManagement.Persistance.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20250821061924_productsInit")]
    partial class productsInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("products")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.CoverageAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoverageLevelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoverageTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CoverageLevelId");

                    b.HasIndex("CoverageTypeId");

                    b.HasIndex("ProductId", "CoverageTypeId", "CoverageLevelId")
                        .IsUnique();

                    b.ToTable("CoverageAvailabilities", "products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.CoverageLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoverageLevelBasisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoverageLevelTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CoverageLevelBasisId");

                    b.HasIndex("CoverageLevelTypeId");

                    b.ToTable("CoverageLevels", "products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.CoverageLevelBasis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CoverageLevelBasises", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.CoverageLevelType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CoverageLevelTypes", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.CoverageType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CoverageTypes", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Products", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ParentProductCategoryId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentProductCategoryId", "Code")
                        .IsUnique();

                    b.ToTable("ProductCatogories", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.ProductCategoryClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductCatogoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductCatogoryId", "ProductId")
                        .IsUnique();

                    b.ToTable("ProductCatogoryClassifications", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.ProductFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("ProductFeatureTypeId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeatureTypeId");

                    b.HasIndex("Code", "ProductFeatureTypeId")
                        .IsUnique();

                    b.ToTable("ProductFeatures", "products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.ProductFeatureAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductFeatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeatureId");

                    b.HasIndex("ProductId", "ProductFeatureId")
                        .IsUnique();

                    b.ToTable("ProductFeatureAvailabilities", "products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.ProductFeatureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProductFeatureTypes", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.OptionalCoverage", b =>
                {
                    b.HasBaseType("Mti.ProductManagement.Domain.Products.CoverageAvailability");

                    b.ToTable("OptionalCoverages", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.SelectableCoverage", b =>
                {
                    b.HasBaseType("Mti.ProductManagement.Domain.Products.CoverageAvailability");

                    b.ToTable("SelectableCoverages", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.CoverageAmount", b =>
                {
                    b.HasBaseType("Mti.ProductManagement.Domain.Products.CoverageLevel");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.ToTable("CoverageAmounts", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.Deductibility", b =>
                {
                    b.HasBaseType("Mti.ProductManagement.Domain.Products.CoverageLevel");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.ToTable("Deductibilities", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.VehicleBrand", b =>
                {
                    b.HasBaseType("Mti.ProductManagement.Domain.Products.ProductFeature");

                    b.ToTable("VehicleBrands", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.VehicleCode", b =>
                {
                    b.HasBaseType("Mti.ProductManagement.Domain.Products.ProductFeature");

                    b.ToTable("VehicleCodes", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.VehicleModel", b =>
                {
                    b.HasBaseType("Mti.ProductManagement.Domain.Products.ProductFeature");

                    b.ToTable("VehicleModels", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.VehicleYear", b =>
                {
                    b.HasBaseType("Mti.ProductManagement.Domain.Products.ProductFeature");

                    b.ToTable("VehicleYears", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.SelectableFeature", b =>
                {
                    b.HasBaseType("Mti.ProductManagement.Domain.Products.ProductFeatureAvailability");

                    b.ToTable("SelectableFeatures", "products");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.CoverageAvailability", b =>
                {
                    b.HasOne("Mti.ProductManagement.Domain.Products.CoverageLevel", "CoverageLevel")
                        .WithMany()
                        .HasForeignKey("CoverageLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.ProductManagement.Domain.Products.CoverageType", "CoverageType")
                        .WithMany()
                        .HasForeignKey("CoverageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.ProductManagement.Domain.Products.Product", "Product")
                        .WithMany("CoverageAvailabilities")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoverageLevel");

                    b.Navigation("CoverageType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.CoverageLevel", b =>
                {
                    b.HasOne("Mti.ProductManagement.Domain.Products.CoverageLevelBasis", "CoverageLevelBasis")
                        .WithMany()
                        .HasForeignKey("CoverageLevelBasisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.ProductManagement.Domain.Products.CoverageLevelType", "CoverageLevelType")
                        .WithMany()
                        .HasForeignKey("CoverageLevelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoverageLevelBasis");

                    b.Navigation("CoverageLevelType");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.ProductCategory", b =>
                {
                    b.HasOne("Mti.ProductManagement.Domain.Products.ProductCategory", "ParentProductCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentProductCategoryId");

                    b.Navigation("ParentProductCategory");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.ProductCategoryClassification", b =>
                {
                    b.HasOne("Mti.ProductManagement.Domain.Products.ProductCategory", "ProductCatogory")
                        .WithMany("ProductCatogoryClassifications")
                        .HasForeignKey("ProductCatogoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.ProductManagement.Domain.Products.Product", "Product")
                        .WithMany("ProductCatogoryClassifications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductCatogory");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.ProductFeature", b =>
                {
                    b.HasOne("Mti.ProductManagement.Domain.Products.ProductFeatureType", "ProductFeatureType")
                        .WithMany()
                        .HasForeignKey("ProductFeatureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFeatureType");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.ProductFeatureAvailability", b =>
                {
                    b.HasOne("Mti.ProductManagement.Domain.Products.ProductFeature", "ProductFeature")
                        .WithMany()
                        .HasForeignKey("ProductFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.ProductManagement.Domain.Products.Product", "Product")
                        .WithMany("ProductFeatureAvailabilities")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductFeature");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.OptionalCoverage", b =>
                {
                    b.HasOne("Mti.ProductManagement.Domain.Products.CoverageAvailability", null)
                        .WithOne()
                        .HasForeignKey("Mti.ProductManagement.Domain.Products.OptionalCoverage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.SelectableCoverage", b =>
                {
                    b.HasOne("Mti.ProductManagement.Domain.Products.CoverageAvailability", null)
                        .WithOne()
                        .HasForeignKey("Mti.ProductManagement.Domain.Products.SelectableCoverage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.CoverageAmount", b =>
                {
                    b.HasOne("Mti.ProductManagement.Domain.Products.CoverageLevel", null)
                        .WithOne()
                        .HasForeignKey("Mti.ProductManagement.Domain.Products.CoverageAmount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.Deductibility", b =>
                {
                    b.HasOne("Mti.ProductManagement.Domain.Products.CoverageLevel", null)
                        .WithOne()
                        .HasForeignKey("Mti.ProductManagement.Domain.Products.Deductibility", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.VehicleBrand", b =>
                {
                    b.HasOne("Mti.ProductManagement.Domain.Products.ProductFeature", null)
                        .WithOne()
                        .HasForeignKey("Mti.ProductManagement.Domain.Products.VehicleBrand", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.VehicleCode", b =>
                {
                    b.HasOne("Mti.ProductManagement.Domain.Products.ProductFeature", null)
                        .WithOne()
                        .HasForeignKey("Mti.ProductManagement.Domain.Products.VehicleCode", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.VehicleModel", b =>
                {
                    b.HasOne("Mti.ProductManagement.Domain.Products.ProductFeature", null)
                        .WithOne()
                        .HasForeignKey("Mti.ProductManagement.Domain.Products.VehicleModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.VehicleYear", b =>
                {
                    b.HasOne("Mti.ProductManagement.Domain.Products.ProductFeature", null)
                        .WithOne()
                        .HasForeignKey("Mti.ProductManagement.Domain.Products.VehicleYear", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.SelectableFeature", b =>
                {
                    b.HasOne("Mti.ProductManagement.Domain.Products.ProductFeatureAvailability", null)
                        .WithOne()
                        .HasForeignKey("Mti.ProductManagement.Domain.Products.SelectableFeature", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.Product", b =>
                {
                    b.Navigation("CoverageAvailabilities");

                    b.Navigation("ProductCatogoryClassifications");

                    b.Navigation("ProductFeatureAvailabilities");
                });

            modelBuilder.Entity("Mti.ProductManagement.Domain.Products.ProductCategory", b =>
                {
                    b.Navigation("ProductCatogoryClassifications");

                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
