// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mti.OrderQueries.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mti.OrderQueries.Persistence.Migrations
{
    [DbContext(typeof(OrderQueriesContext))]
    [Migration("20250827092112_initOrderQueries7")]
    partial class initOrderQueries7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("order_queries")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mti.OrderQueries.Domain.OrdersWharehouse.ApplicationDim", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationCollateralNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ApplicationCustomerInfoNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("ApplicationOriginalId")
                        .HasColumnType("bigint");

                    b.Property<string>("ApplicationPayPlan")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("ApplicationPolicyEffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ApplicationPolicyExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("ApplicationPolicyNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ApplicationPolicyPreviousNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ApplicationPolicyType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ApplicationRefDetailNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ApplicationRefNoticeNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ApplicationRefQuotation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ApplicationRemark")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ApplicationSource")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ApplicationStatus")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("ApplicationStatusMessage")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ApplicationSystemId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ApplicationTransID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("ApplicationDims", "order_queries");
                });

            modelBuilder.Entity("Mti.OrderQueries.Domain.OrdersWharehouse.ContactMechanismDim", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContactMechanismId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactMechanismTypeCode")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PartyDimKey")
                        .HasColumnType("uuid");

                    b.Property<string>("PostalAddressAlley")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PostalAddressBuilding")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PostalAddressDisplayName")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("PostalAddressDistrict")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PostalAddressFloor")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PostalAddressHouseNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PostalAddressName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PostalAddressProvince")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PostalAddressRoad")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PostalAddressRoom")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PostalAddressSubDistrict")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PostalAddressVillage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PostalAddressVillageNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PostalAddressZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("PartyDimKey");

                    b.ToTable("ContactMechanismDims", "order_queries");
                });

            modelBuilder.Entity("Mti.OrderQueries.Domain.OrdersWharehouse.InsuredAssetDim", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssetName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("AssetTypeCode")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<string>("VehicleBrand")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<float?>("VehicleCc")
                        .HasColumnType("real");

                    b.Property<string>("VehicleChassis")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VehicleColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VehicleEngine")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleModel")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int?>("VehiclePassenger")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleRegisterNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleRegisterProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("VehicleRegisterYear")
                        .HasColumnType("integer");

                    b.Property<float?>("VehicleSeat")
                        .HasColumnType("real");

                    b.Property<float?>("VehicleTonnage")
                        .HasColumnType("real");

                    b.Property<float?>("VehicleWeight")
                        .HasColumnType("real");

                    b.HasKey("Key");

                    b.HasIndex("AssetTypeCode");

                    b.ToTable("InsuredAssetDims", "order_queries");
                });

            modelBuilder.Entity("Mti.OrderQueries.Domain.OrdersWharehouse.OrderDim", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderLoanNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("OrderSaleDate")
                        .HasColumnType("date");

                    b.Property<string>("Orders_TenantId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("OrderLoanNumber");

                    b.HasIndex("OrderSaleDate");

                    b.HasIndex("OrderSaleDate", "OrderLoanNumber");

                    b.ToTable("OrderDims", "order_queries");
                });

            modelBuilder.Entity("Mti.OrderQueries.Domain.OrdersWharehouse.OrderItemFact", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationDimKey")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InsuredAssetDimKey")
                        .HasColumnType("uuid");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderDimKey")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrderItemOrderedForId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OrderItemPrice")
                        .HasColumnType("numeric");

                    b.Property<long>("OrderItemQuantity")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderItemSeq")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ProductDimKey")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("ApplicationDimKey");

                    b.HasIndex("InsuredAssetDimKey");

                    b.HasIndex("OrderDimKey");

                    b.HasIndex("OrderItemId")
                        .IsUnique();

                    b.HasIndex("ProductDimKey");

                    b.ToTable("OrderItemFacts", "order_queries");
                });

            modelBuilder.Entity("Mti.OrderQueries.Domain.OrdersWharehouse.OrderItemPartyRoleDim", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderItemFactKey")
                        .HasColumnType("uuid");

                    b.Property<long>("OrderItemRoleSeq")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderItemRoleTypeCode")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("PartyDimKey")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("OrderItemFactKey");

                    b.HasIndex("PartyDimKey");

                    b.ToTable("OrderItemPartyRoleDims", "order_queries");
                });

            modelBuilder.Entity("Mti.OrderQueries.Domain.OrdersWharehouse.PartyDim", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalOrganizationFederalTaxIdNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("OrganizationReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Parties_TenantId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartyTitleName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PartyTypeCode")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateOnly?>("PersonBirthDate")
                        .HasColumnType("date");

                    b.Property<string>("PersonCardId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PersonFirstName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PersonHeight")
                        .HasColumnType("integer");

                    b.Property<string>("PersonLastName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PersonMiddleName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PersonWeight")
                        .HasColumnType("integer");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("PartyTypeCode");

                    b.ToTable("PartyDims", "order_queries");
                });

            modelBuilder.Entity("Mti.OrderQueries.Domain.OrdersWharehouse.ProductDim", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductCampaign")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProductCategoryTypeCodes")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ProductPackage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProductRefPolicyType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductWorkshop")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Products_TenantId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("ProductCategoryTypeCodes");

                    b.HasIndex("ProductCode", "Products_TenantId")
                        .IsUnique();

                    b.ToTable("ProductDims", "order_queries");
                });

            modelBuilder.Entity("Mti.OrderQueries.Domain.OrdersWharehouse.ContactMechanismDim", b =>
                {
                    b.HasOne("Mti.OrderQueries.Domain.OrdersWharehouse.PartyDim", "PartyDim")
                        .WithMany("ContactMechanisms")
                        .HasForeignKey("PartyDimKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyDim");
                });

            modelBuilder.Entity("Mti.OrderQueries.Domain.OrdersWharehouse.OrderItemFact", b =>
                {
                    b.HasOne("Mti.OrderQueries.Domain.OrdersWharehouse.ApplicationDim", "ApplicationDim")
                        .WithMany()
                        .HasForeignKey("ApplicationDimKey");

                    b.HasOne("Mti.OrderQueries.Domain.OrdersWharehouse.InsuredAssetDim", "InsuredAssetDim")
                        .WithMany()
                        .HasForeignKey("InsuredAssetDimKey");

                    b.HasOne("Mti.OrderQueries.Domain.OrdersWharehouse.OrderDim", "OrderDim")
                        .WithMany()
                        .HasForeignKey("OrderDimKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.OrderQueries.Domain.OrdersWharehouse.ProductDim", "ProductDim")
                        .WithMany()
                        .HasForeignKey("ProductDimKey");

                    b.Navigation("ApplicationDim");

                    b.Navigation("InsuredAssetDim");

                    b.Navigation("OrderDim");

                    b.Navigation("ProductDim");
                });

            modelBuilder.Entity("Mti.OrderQueries.Domain.OrdersWharehouse.OrderItemPartyRoleDim", b =>
                {
                    b.HasOne("Mti.OrderQueries.Domain.OrdersWharehouse.OrderItemFact", "OrderItemFact")
                        .WithMany("OrderItemPartyRoleDims")
                        .HasForeignKey("OrderItemFactKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.OrderQueries.Domain.OrdersWharehouse.PartyDim", "PartyDim")
                        .WithMany()
                        .HasForeignKey("PartyDimKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItemFact");

                    b.Navigation("PartyDim");
                });

            modelBuilder.Entity("Mti.OrderQueries.Domain.OrdersWharehouse.OrderItemFact", b =>
                {
                    b.Navigation("OrderItemPartyRoleDims");
                });

            modelBuilder.Entity("Mti.OrderQueries.Domain.OrdersWharehouse.PartyDim", b =>
                {
                    b.Navigation("ContactMechanisms");
                });
#pragma warning restore 612, 618
        }
    }
}
